### ISSUE TITLE
Applying changes to files...

### ISSUE THREAD

**Issue by MICHAEL-888** [leminlimez/Nugget#274]
Hi,I met a problem that I cannot apply any settings to my iphone. Nugget always shows "Applying changes to files".I need help🙁
Nugget is running on macos sequoia 15.1.1 ,and my iphone is running ios18.1(22B5075a).
I've disable "Find my iPhone" in settings.
<img width="986" alt="截屏2024-12-12 12 51 32" src="https://github.com/user-attachments/assets/11c106d4-531c-459f-8d85-8d848f262d60" />
<img width="986" alt="截屏2024-12-12 12 52 41" src="https://github.com/user-attachments/assets/3be127fa-094b-44e6-9d9f-c543af8a96e3" />

**Comment by chuck00000** [comment]
same issue on Windows here, the command windows shows
![Screenshot 2024-12-12 123710](https://github.com/user-attachments/assets/3ec99c0a-0e59-4ad2-a1fd-a17ca3568c9b)
 waste my 1 hour time

**Comment by nitol** [comment]
same here:
Traceback (most recent call last):
  File "gui\main_window.py", line 917, in on_applyTweaksBtn_clicked
  File "devicemanagement\device_manager.py", line 325, in apply_changes
  File "tweaks\tweak_classes.py", line 189, in apply_tweak
AttributeError: 'MobileGestaltTweak' object has no attribute 'subkey'

**Comment by Mahrad2009YP** [comment]
Hi
@leminlimez 
You say: 
Mobilegestalt tweaks will never support iOS 18.2+. Do not make an issue about it.

it means we can't have dynamic island and apple intelligence on our unsupported devices anytime?
or we have them on next release?

**Comment by luke2023** [comment]
same here, but the 4.1 version works fine

**Comment by Agustine808** [comment]
i think this version needed to re upload after the fix,i changed to beta to stable can't apply any patches!

**Comment by nitol** [comment]
Off topic here- is AI and other tweaks working on latest 18.2 public?

**Comment by leminlimez** [comment]
known issue, will be fixed next update when i have time to make it

**Comment by Agustine808** [comment]
thanks for your response,that means with this update we can't apply anything simply thats right?

**Comment by leminlimez** [comment]
seems to only impact mobilegestalt tweaks. If you really need them, you can downgrade to Nugget v4.1 until I can fix it, or wait a day or so for v4.2.1

**Comment by Mahrad2009YP** [comment]
@leminlimez 
can I have AI and dynamic island on iOS 18.2 on next update?
or we can't have them anytime?
please answer 🙏

**Comment by Agustine808** [comment]
> seems to only impact mobilegestalt tweaks. If you really need them, you can downgrade to Nugget v4.1 until I can fix it, or wait a day or so for v4.2.1
thanks for your support,i will wait for sure,only one thing i wanna whats that aod vibrancy actually brings,can we wakeup device with a single tap from aod?

**Comment by leminlimez** [comment]
Fixed in v4.2.1
